export const ptBr = {
  "pt-BR": {
    richtexteditor: {
      alignments: "Alinhamentos",
      justifyLeft: "Alinhar à esquerda",
      justifyCenter: "Alinhar ao centro",
      justifyRight: "Alinhar à direita",
      justifyFull: "Alinhar justificar",
      fontName: "Nome da fonte",
      fontSize: "Tamanho da fonte",
      fontColor: "Cor da fonte",
      backgroundColor: "Cor de fundo",
      bold: "Negrito",
      italic: "Itálico",
      underline: "Sublinhado",
      strikethrough: "Tachado",
      clearFormat: "Limpar formato",
      clearAll: "Limpar tudo",
      cut: "Cortar",
      copy: "Cópia de",
      paste: "Colar",
      unorderedList: "Lista com marcadores",
      orderedList: "Lista numerada",
      indent: "Aumentar recuo",
      outdent: "Recuar devagar",
      undo: "Desfazer",
      redo: "Refazer",
      superscript: "Sobrescrito",
      subscript: "Subscrito",
      createLink: "Insira o hyperlink",
      openLink: "Link aberto",
      editLink: "Editar Link",
      removeLink: "Remover link",
      image: "Inserir Imagem",
      replace: "Substituir",
      align: "Alinhar",
      caption: "Legenda da imagem",
      remove: "Retirar",
      insertLink: "Inserir link",
      display: "Exibição",
      altText: "Texto Alternativo",
      dimension: "Alterar tamanho",
      fullscreen: "Maximizar",
      maximize: "Maximizar",
      minimize: "Minimizar",
      lowerCase: "Minúsculas",
      upperCase: "Maiúsculas",
      print: "Impressão",
      formats: "Formatos",
      sourcecode: "Visualização de código",
      preview: "Pré-visualização",
      viewside: "ViewSide",
      insertCode: "Insira Código",
      linkText: "Texto de exibição",
      linkTooltipLabel: "Título",
      linkWebUrl: "Endereço da Web",
      linkTitle: "Digite um título",
      linkurl: "http://exemplo.com",
      linkOpenInNewWindow: "Abrir link em nova janela",
      linkHeader: "Inserir link",
      dialogInsert: "Inserir",
      dialogCancel: "Cancelar",
      dialogUpdate: "Atualizar",
      imageHeader: "Inserir Imagem",
      imageLinkHeader: "Você também pode fornecer um link da web",
      mdimageLink: "Forneça um URL para sua imagem",
      imageUploadMessage: "Solte a imagem aqui ou navegue para fazer upload",
      imageDeviceUploadMessage: "Clique aqui para fazer o upload",
      imageAlternateText: "Texto alternativo",
      alternateHeader: "Texto Alternativo",
      browse: "Squeaky toy",
      imageUrl: "http://example.com/image.png",
      imageCaption: "Rubrica",
      imageSizeHeader: "Tamanho da imagem",
      imageHeight: "Altura",
      imageWidth: "Largura",
      textPlaceholder: "Inserir texto",
      styles: "Estilos",
      imageInsertLinkHeader: "Inserir link",
      editImageHeader: "Editar imagem",
      alignmentsDropDownLeft: "Alinhar à esquerda",
      alignmentsDropDownCenter: "Alinhar ao centro",
      alignmentsDropDownRight: "Alinhar à direita",
      alignmentsDropDownJustify: "Alinhar justificar",
      imageDisplayDropDownInline: "Na linha",
      imageDisplayDropDownBreak: "Pausa",
      pasteFormat: "Colar formato",
      pasteFormatContent: "Escolha a ação de formatação",
      plainText: "Texto simples",
      cleanFormat: "Limpar formato",
      keepFormat: "Manter",
      fileManager: "Gerenciador de arquivos",
      fileDialogHeader: "Navegador de arquivos",
      formatsDropDownParagraph: "Parágrafo",
      formatsDropDownQuotation: "Citação",
      formatsDropDownHeading1: "Título 1",
      formatsDropDownHeading2: "Título 2",
      formatsDropDownHeading3: "Título 3",
      formatsDropDownHeading4: "Título 4",
      formatsDropDownCode: "Hipertexto",
    },
  },
};
